version: "3.8"

services:
  squadly_location:
    build: ./squadly-location
    ports:
      - 5000:5000
    env_file:
      - ./squadly-location/.env
    volumes:
      - ./squadly-location:/app
  squadly_squads:
    build: ./squadly-squads
    ports:
      - 5001:5001
    env_file:
      - ./squadly-squads/.env
    volumes:
      - ./squadly-squads:/app
  mongo_db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE="squadly-location"
      - MYSQL_ROOT_PASSWORD="password"
    volumes:
      - mysqlData:/var/lib/mysql

volumes:
  mongoData:
  mysqlData:
