version: "3.8"

services:
  squadly_location:
    build: ./squadly-location
    env_file:
      - ./squadly-location/.env
    ports:
      - 5000
    depends_on:
      - nginx
      - mysql_db

  squadly_squads:
    build: ./squadly-squads
    env_file:
      - ./squadly-squads/.env
    ports:
      - 5001
    environment:
      - DB_URI=mongodb://mongo_db/squadly-squads
    depends_on:
      - nginx
      - mongo_db

  mongo_db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db

  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE="squadly-location"
      - MYSQL_ROOT_PASSWORD="password"
    volumes:
      - mysqlData:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongoData:
  mysqlData:
